"""Export label-prefix tokens, class positions, label names and MITRE rules
into release/hyperids_labels.h for the static C binary."""
from __future__ import annotations
from pathlib import Path
from transformers import AutoTokenizer
import schema

ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = ROOT / "model" / "checkpoints_gpu" / "final_model_v2"
OUT = ROOT / "release" / "hyperids_labels.h"

IDS = schema.all_label_ids()
VERDICT = schema.verdict_ids()
ACTIONS = schema.action_ids()


def main():
    tok = AutoTokenizer.from_pretrained(str(MODEL_DIR), add_prefix_space=True)
    # tokenize the label prefix WITHOUT special tokens, then prepend [CLS].
    # (the trailing [SEP] is appended after the command at inference time)
    prefix_s = "".join(f"<<LABEL>>{l}" for l in IDS) + "<<SEP>>"
    ids = [tok.cls_token_id] + tok(prefix_s, add_special_tokens=False)["input_ids"]
    cls_pos = [i for i, t in enumerate(ids) if t == 30522]
    assert len(cls_pos) == 31, f"expected 31 class tokens, got {len(cls_pos)}"
    sep_pos = [i for i, t in enumerate(ids) if t == 30523]
    assert len(sep_pos) == 1

    rules = schema.action_attck()
    # unique tactic / technique names
    tactics = sorted({t for r in rules.values() for t in r["tactics"]})
    techniques = sorted({t for r in rules.values() for t in r["techniques"]})
    tact_idx = {t: i for i, t in enumerate(tactics)}
    tech_idx = {t: i for i, t in enumerate(techniques)}

    def c_arr(name, vals):
        return f"static const int {name}[{len(vals)}] = {{{', '.join(map(str, vals))}}};"

    lines = []
    lines.append("/* Auto-generated by export_c_labels.py — DO NOT EDIT. */")
    lines.append("#ifndef HYPERIDS_LABELS_H")
    lines.append("#define HYPERIDS_LABELS_H")
    lines.append("")
    lines.append(f"#define N_LABELS 31")
    lines.append(f"#define N_VERDICT 3")
    lines.append(f"#define N_ACTION 28")
    lines.append(f"#define LABEL_PREFIX_LEN {len(ids)}")
    lines.append(f"#define N_TACTICS {len(tactics)}")
    lines.append(f"#define N_TECHNIQUES {len(techniques)}")
    lines.append("")
    lines.append(c_arr("label_prefix_tokens", ids))
    lines.append(c_arr("class_token_pos", cls_pos))
    lines.append("")
    # label names
    lines.append("static const char *const LABEL_NAMES[31] = {")
    for l in IDS:
        lines.append(f'    "{l}",')
    lines.append("};")
    lines.append("")
    # verdict names (short)
    lines.append('static const char *const VERDICT_NAMES[3] = {"benign", "suspicious", "malicious"};')
    lines.append("")
    # action short names (without action. prefix)
    lines.append("static const char *const ACTION_NAMES[28] = {")
    for a in ACTIONS:
        lines.append(f'    "{a.removeprefix("action.")}",')
    lines.append("};")
    lines.append("")
    # tactics/techniques names
    lines.append("static const char *const TACTIC_NAMES[N_TACTICS] = {")
    for t in tactics:
        lines.append(f'    "{t}",')
    lines.append("};")
    lines.append("static const char *const TECHNIQUE_NAMES[N_TECHNIQUES] = {")
    for t in techniques:
        lines.append(f'    "{t}",')
    lines.append("};")
    lines.append("")
    # per-action tactic/technique bitmap
    lines.append(f"static const unsigned int ACTION_TACTIC_BITMAP[28] = {{")
    for a in ACTIONS:
        r = rules[a]
        bits = sum(1 << tact_idx[t] for t in r["tactics"])
        lines.append(f"    0x{bits:x}u,")
    lines.append("};")
    lines.append(f"static const unsigned int ACTION_TECH_BITMAP[28] = {{")
    for a in ACTIONS:
        r = rules[a]
        bits = sum(1 << tech_idx[t] for t in r["techniques"])
        lines.append(f"    0x{bits:x}u,")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* HYPERIDS_LABELS_H */")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: prefix_len={len(ids)} class_pos={cls_pos} tactics={len(tactics)} techniques={len(techniques)}")


if __name__ == "__main__":
    main()
